frame_workers_tm_food_rescue_food_app_homepage:
    pattern:  /
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Default:index }

frame_workers_tm_food_rescue_food_app_dashboard:
    pattern:  /dashboard/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Dashboard:index }

frame_workers_tm_food_rescue_food_app_my_products:
    pattern:  /myproducts/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:MyProducts:index }

frame_workers_tm_food_rescue_food_app_recipes:
    pattern:  /recipes/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Recipes:index }
    
frame_workers_tm_food_rescue_food_app_recipe:
    pattern: /recipes/view/{recipeid}
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Recipes:RecipieView }

frame_workers_tm_food_rescue_food_app_logout:
    pattern:  /logout/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Login:logout }


frame_workers_tm_food_rescue_food_app_settings:
    pattern: /settings/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Settings:index }

frame_workers_tm_food_rescue_app_products_list:
    pattern: /productslist/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:ProductList:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
