frame_workers_tm_food_rescue_food_app_homepage:
    pattern:  /
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Default:index }

frame_workers_tm_food_rescue_food_app_dashboard:
    pattern:  /dashboard/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Dashboard:index }

frame_workers_tm_food_rescue_food_app_my_products:
    pattern:  /myproducts/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:MyProducts:index }

frame_workers_tm_food_rescue_food_app_recipes:
    pattern:  /recipes/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Recipes:index }

frame_workers_tm_food_rescue_food_app_login:
    pattern:  /login/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Login:index }

frame_workers_tm_food_rescue_food_app_settings:
    pattern: /settings/
    defaults: { _controller: FrameWorkersTMFoodRescueFoodAppBundle:Settings:index }
