frame_workers_tm_food_rescue_food_app:
    resource: "@FrameWorkersTMFoodRescueFoodAppBundle/Resources/config/routing.yml"
    prefix:   /

#Rolando demo
#acme_user:
#    resource: "@AcmeUserBundle/Resources/config/routing.yml"
#    prefix:   /

#Rolando demo
#testukas_testas:
#    resource: "@TestukasTestasBundle/Resources/config/routing.yml"
#    prefix:   /




